export const AUTH_START = 'AUTH_START';
export const IS_LOADING = 'IS_LOADING';

export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';

export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_END = 'AUTH_END';

export const LOGOUT = 'LOGOUT';

export const ADD_TODO_START = 'ADD_TODO_START';
export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS';
export const ADD_TODO_FAIL = 'ADD_TODO_FAIL';

export const DELETE_TODO_START = 'DELETE_TODO_START';
export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS';
export const DELETE_TODO_FAIL = 'DELETE_TODO_FAIL';
